import type { Metadata } from "next";
import "./globals.css";
import { AudioProvider } from "@/lib/audio/AudioProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <AudioProvider>{children}</AudioProvider>
      </body>
    </html>
  );
}
